#!/bin/bash
# For generating multiple starting points for ReCom testing
scripts/random_map.py --state NC --plantype congress --offset 0 --output temp/NC20C_start_00.csv --log temp/NC20C_log_00.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 1 --output temp/NC20C_start_01.csv --log temp/NC20C_log_01.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 2 --output temp/NC20C_start_02.csv --log temp/NC20C_log_02.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 3 --output temp/NC20C_start_03.csv --log temp/NC20C_log_03.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 4 --output temp/NC20C_start_04.csv --log temp/NC20C_log_04.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 5 --output temp/NC20C_start_05.csv --log temp/NC20C_log_05.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 6 --output temp/NC20C_start_06.csv --log temp/NC20C_log_06.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 7 --output temp/NC20C_start_07.csv --log temp/NC20C_log_07.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 8 --output temp/NC20C_start_08.csv --log temp/NC20C_log_08.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
scripts/random_map.py --state NC --plantype congress --offset 9 --output temp/NC20C_start_09.csv --log temp/NC20C_log_09.txt --roughlyequal 0.01 --data ../rdabase/data/NC/NC_2020_data.csv --shapes ../rdabase/data/NC/NC_2020_shapes_simplified.json --graph ../rdabase/data/NC/NC_2020_graph.json --no-debug
